### ISSUE TITLE
Slow browsing into songs list

### ISSUE THREAD

**Issue by coolky** [tehkillerbee/mopidy-tidal#15] opened 2020-04-21 11:30 UTC
This is my environment:
Manjaro 19.02 x64
python 3.8.2
mopidy 3.0.2
mopidy-tidal 0.2.2

I'm using mopidy-musicbox-webclient, but I have the same issue with all mopidy webclients (and other gtk mpd client). When I'm trying to browse into an album or playlist I have to wait a lot of time until I can choose to play one song, this appens only into tidal browsing.

The logs are crystal clear:

> INFO     2020-04-21 13:13:43,033 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:6164258:102387249:102387250'
INFO     2020-04-21 13:13:43,761 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:43,761 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:8149304:86638235:86638238'
INFO     2020-04-21 13:13:44,353 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:44,354 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:4818468:93636554:93636556'
INFO     2020-04-21 13:13:44,921 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:44,921 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:9817165:96843255:96843256'
INFO     2020-04-21 13:13:45,530 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:45,530 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:5701795:93139653:93139654'
INFO     2020-04-21 13:13:46,112 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:46,113 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:16056:101269540:101269541'
INFO     2020-04-21 13:13:46,716 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:46,717 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:4579716:97132833:97132834'
INFO     2020-04-21 13:13:47,278 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:47,278 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:8049126:82247412:82247413'
INFO     2020-04-21 13:13:47,838 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks
INFO     2020-04-21 13:13:47,838 [3462:TidalBackend-6] mopidy_tidal.library
  Lookup uris 'tidal:track:5023237:78196153:78196154'
INFO     2020-04-21 13:13:48,443 [3462:TidalBackend-6] mopidy_tidal.library
  Returning 1 tracks

It takes 0.5-1 seconds for each track, so even if an album contains 10 tracks I have to wait at least 6-10 seconds. Can you implement multithread, async or reviewing code for speed up the browsing feature?

Thank you very much

**Comment by tehkillerbee** [comment] 2020-05-11 20:22
Good suggestion. I noticed the same issue and I think it causes some webclients to timeout for this very reason. 

It would be nice to confirm that this is an issue specific for the Tidal plugin, maybe by comparing with the way this is implemented in other plugins (spotify etc.). Unfortunately, I am not the original author of this project so I am not 100% familiar with the sources yet. But feel free to create a pull request, if you find a solution.

**Comment by coolky** [comment] 2020-05-15 08:41
I think you don't have any issue becouse you have a very perfomance internet speed, I debugged deeper and I discovered that the latency is the method "session.get_album_tracks" that calls tidalapi: `json_obj = self.request('GET', url, params).json()`

This GET request with my internet speed takes ~500ms

I think I can implement an sqlite database that be populated first time you call the track and then, instead of doing a request to tidal api, calls internal db, it's very many quickier.

But now we have a problem much more important..... The tidal api doesn't work anymore:

> {"status":401,"subStatus":6004,"userMessage":"Invalid token"}
ERROR    2020-05-15 10:16:03,120 [7536:TidalBackend-6] pykka
  Unhandled exception in TidalBackend (urn:uuid:84e58c0d-f860-4560-9d4b-223a6346fe7f):
Traceback (most recent call last):
  File "/WORK/TIDAL-PROJECT/venv/lib/python3.8/site-packages/pykka/_actor.py", line 186, in _actor_loop
    self.on_start()
  File "/WORK/TIDAL-PROJECT/venv/lib/python3.8/site-packages/mopidy_tidal/backend.py", line 35, in on_start
    if self._session.login(self._username, self._password):
  File "/WORK/TIDAL-PROJECT/venv/lib/python3.8/site-packages/tidalapi/__init__.py", line 86, in login
    request.raise_for_status()
  File "/WORK/TIDAL-PROJECT/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/login/username?token=kgsOOmYk3zShYrNP
ERROR    2020-05-15 10:16:03,121 [7536:MainThread] mopidy.commands
  Actor died: TidalBackend (urn:uuid:84e58c0d-f860-4560-9d4b-223a6346fe7f) stopped before handling the message


Can you do an additional test?

**Comment by DerNuntius** [comment] 2020-05-15 13:46
[https://github.com/tehkillerbee/mopidy-tidal/issues/19](https://github.com/tehkillerbee/mopidy-tidal/issues/19)
> Yes, the api token is not valid anymore. This is also apparent from the python-tidal package that mopidy-tidal depends on:
> https://github.com/tamland/python-tidal/issues
> 
> I have noticed that other (illegal?) tidal tools has updated their token although I am not exactly sure where this token has been obtained: hZ9wuySZCmpLLiui
> I have changed my python-tidal installation to use this token and it now works again.
> I suggest we wait for an update of the python-tidal package.

**Comment by tehkillerbee** [comment] 2020-05-15 18:25
@coolky Good idea using a local cache / db. Although, I wonder if this should be implemented as part of mopidy-tidal or as part as the python-tidal / tidalapi instead...

**Comment by kmbt** [comment] 2020-05-18 20:26
Hi, I experience similar problems while browsing/searching using web clients (Iris and Mopidy Mobile). What I can see is that after issuing some GUI commands, the Tidal Backend receives large amount of lookup requests and processes them sequentially thus blocking any further requests from being processed until the resulting queue finishes.

The sequential and blocking nature of the request queue seems to be the main showstopper.

I wonder if there is any way to gain control over the processing queue. If the queue could be controlled it might be possible to process it in parallel or give certain requests greater priority.

**Comment by srob** [comment] 2020-06-30 16:22
I am also seeing the same problem. This is not often that serious with albums, but with large playlists, of several hundred tracks, it means that mopidy-tidal is effectively not very usable.

**Comment by tehkillerbee** [comment] 2020-07-02 08:04
@kmbt @srob I agree this is a serious issue. I believe there are two possible causes; either caused by mopidy-tidal or the tidalapi backend itself.

A. mopidy-tidal requests individual songs, in a sequence, instead of requesting the complete playlist tracks through the correct tidalapi calls. After looking into how mopidy-tidal populates the playlists, I believe we should be using a different approach. Currently, it looks like each track is generated in a sequence:
https://github.com/tehkillerbee/mopidy-tidal/blob/df29b2b71afa8e4a67ad280143f436a3d7bc81bd/mopidy_tidal/playlists.py#L62
However, the tidalapi supports a number of functions to directly obtain the tracks within an album and/or a playlist:
https://github.com/tamland/python-tidal/blob/251ed480cb8ba33eeec16436593e409c49540122/tidalapi/__init__.py#L138

I believe we should use the above calls instead.

B. Another possible reason could be the tidal backend itself requests the songs in a playlist/album sequentially. In this case, the issue must be fixed in the tidalapi / python-tidal library, unless a local cache is used by mopidy-tidal. I don't think this is a likely cause.

**Comment by MrSurly** [comment] 2021-02-08 20:27
Any progress here?  I'm hitting this myself. 

I can dig in and help; though I'm not familiar with the Mopidy plugin system.

**Comment by tehkillerbee** [comment] 2021-02-08 20:42
Sorry, I have not attempted to make any improvements to the slow browsing. However, in a recent pull request #27 , a couple of improvements were made (album art caching and other minor improvements). It is my plan to add these changes and see if they improve the browsing experience. I did not merge these changes, as they are not tested on Python 3 and since the OAuth login is not currently supported by https://github.com/tamland/python-tidal

**Comment by MrSurly** [comment] 2021-02-08 23:45
Having looked at this a bit:
<hr>
Using **Iris**
I'm mostly looking at Browse --> Tidal --> Moods --> [a mood]

This triggers two calls to the mopidy-tidal backend:
`browse([playlist])` // moods are a type of playlist
`lookup([playlist])`

The `browse` call returns a list of all the tracks.
The `lookup` call _does not_ return a list of tracks.  I modified it to do so, but it didn't help.

Iris will use the the list of tracks from `browse` to do a `lookup` on _each_ track.
<hr>
Using **musicbox_webclient**:

Perform the same navigation as above.

`browse([playlist])`
You do _not_ see a call to `lookup([playlist])`

musicbox_webclient will _immediately_ show the list returned by `browse`, but have a "loading data please wait" spinner while it calls `lookup` on each track.  After that has finished, the displayed tracklist is updated with the details, and you can play them.
<hr>
Current conclusion/hypothesis: 

* The Tidal API does provide efficient ways of obtaining the detailed tracklist.
* `mopidy-tidal` should _probably_ implement `lookup([playlist])` so that it returns a list of tracks
* Iris doesn't seem to be doing a good job of keeping the user up-to-date with what it's doing (i.e. fetching tracks in the background), and eventually times out.  musicbox_webclient does a better job in this regard.
* Both clients should simply use `lookup([playlist])` to quickly get a list of tracks.

My conclusions (especially the last one) are probably clouded (or just plain wrong) because of my unfamiliarity with MPD & Mopidy.  It's hard to find documentation on the intended flow, or what extensions _should_ be providing to the Backend API that they are implementing.

**Comment by tehkillerbee** [comment] 2022-01-19 20:14
Fixed in #30

**Closed by tehkillerbee** 2022-01-19 20:14 UTC
