### ISSUE TITLE
Selecting HI_RES (OAUTH) still plays HI_RES_LOSSLESS

### ISSUE THREAD

**Issue by fmarzocca** [tehkillerbee/mopidy-tidal#168] opened 2024-03-30 15:18 UTC
I have set HI_RES and OAUTH, as confirmed by the log:

```
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend Mopidy-Tidal version: v0.3.6
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend Python-Tidal version: v0.7.5
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend PKCE login web server port: 8989
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend Quality: HI_RES
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend Authentication: OAuth
Mar 29 17:40:29 pab mopidy[642]: WARNING  [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend AUTO login implies lazy connection, setting lazy=Tru>
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend Login method: AUTO
Mar 29 17:40:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.backend Using default client id & client secret from python->
```

but it still plays HI_RES_LOSSLESS/FLAC for tracks that also have HI_RES/MQA available:

```
Mar 30 12:56:17 pab mopidy[642]: DEBUG    [mopidy-tidal-images-_0] mopidy_tidal.library Image URL for 'tidal:album:244731': 'https://resources.tidal.com/images/4f9e1be6/>
Mar 30 13:00:28 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.playback TIDAL uri: tidal:track:15796:77661290:77661291
Mar 30 13:00:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.playback MimeType:application/dash+xml
Mar 30 13:00:29 pab mopidy[642]: INFO     [TidalBackend-3 (_actor_loop)] mopidy_tidal.playback Starting playback of track:77661291, (quality:HI_RES_LOSSLESS, codec:flac,>
```
The track uri `tidal:track:15796:77661290:77661291` has MQA capability, but it plays HI_RES_LOSSLESS/FLAC:

```
./tidalQuality.py "tidal:track:15796:77661290:77661291"
Playing: {"quality": "HI_RES_LOSSLESS", "codec": "flac"}
Track metadata: ['LOSSLESS', 'HIRES_LOSSLESS', 'MQA']
````
Shouldn't `TidalPlaybackProvider` take care of this?

**Comment by tehkillerbee** [comment] 2024-03-30 15:46
Hires lossless playback should not be possible if oauth is used. I believe this is related to the bug I talked about in the other issue. You can check what is_pkce is set to in your session json file. 

Try to delete your oauth session and sign in again and see if it helps.

**Comment by fmarzocca** [comment] 2024-03-30 16:17
> Hires lossless playback should not be possible if oauth is used.

I know That's why I opened the ticket.
This is in `tidal-oauth.json`:
`"is_pkce": {"data": true}`

> Try to delete your oauth session and sign in again and see if it helps.

Again?.... :-(

**Comment by fmarzocca** [comment] 2024-03-30 17:30
I have deleted oauth session and signed in again. Now the track is correctly reported as HI-RES/MQA, but in the session json I always have: `is_pkce": {"data": true}`

**Comment by tehkillerbee** [comment] 2024-04-02 05:09
Yep, I believe I have found the cause of this bug. It will be fixed in the next release of mopidy-tidal / tidalapi.

**Closed** 2024-04-02 05:26 UTC

**Comment by fmarzocca** [comment] 2024-04-08 14:54
@tehkillerbee 
Johannes, I am experiencing this problem every day. As I don't currently have the budget to buy a new DAC, but my converter works great with MQA, I would like to continue using my mopidy's playlists.

If you don't have planned to publish the new release soon, can I have the patch to apply locally?

**Comment by tehkillerbee** [comment] 2024-04-08 15:00
This is already fixed on the latest master. 

You could always install that until the next release of tidalapi/ mopidy-tidal is ready.

**Comment by fmarzocca** [comment] 2024-04-08 15:03
Ah, ok. Does it extends to tidalapi too?

**Comment by tehkillerbee** [comment] 2024-04-08 15:05
The issue is caused by tidalapi but probably the best idea to update both mopidy-tidal and tidalapi.

**Comment by fmarzocca** [comment] 2024-04-09 14:07
> Otherwise I'll try to get the next release ready ASAP

Thanks!

**Comment by fmarzocca** [comment] 2024-04-09 14:31
I am afraid it is still there...
With OAUTH and HI_RES, the track `tidal:track:2579:77622430:77622437` plays at:
`{"quality": "HI_RES_LOSSLESS", "codec": "flac"}`

**Comment by fmarzocca** [comment] 2024-04-09 14:37
I have deleted the session file and now it looks OK. I will report any future issue.
