### ISSUE TITLE
Tidal extension ignored in config by Mopidy server

### ISSUE THREAD

**Issue by Wallmersbacher** [tehkillerbee/mopidy-tidal#80] opened 2022-09-13 07:06 UTC
The recent Mopidy 3.3.0 version seems to ignore the Tidal extension in the config. 
I added the exact same config as described on the project page but the Mopidy journal returns just an error:

`mopidy[4041]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.3.0
mopidy[4041]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
mopidy[4041]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
mopidy[4041]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
mopidy[4041]: INFO     [MainThread] mopidy.config Loading config from command line options
**mopidy[4041]: WARNING  [MainThread] mopidy.config Ignoring config section 'tidal' because no matching extension was found**
mopidy[4041]: INFO     [MainThread] mopidy.__main__ Enabled extensions: stream, mpd, http, file, iris, m3u, softwaremixer
mopidy[4041]: INFO     [MainThread] mopidy.__main__ Disabled extensions: spotify, local
`

The installation process didn't return any errors so I just assumed everything worked fine.

`raspberrypi:/etc/mopidy $ pip3 install Mopidy-Tidal
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Mopidy-Tidal
  Downloading https://www.piwheels.org/simple/mopidy-tidal/Mopidy_Tidal-0.2.7-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: requests>=2.0.0 in /usr/lib/python3/dist-packages (from Mopidy-Tidal) (2.25.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from Mopidy-Tidal) (52.0.0)
Collecting tidalapi<0.7.0,>=0.6.9
  Downloading https://www.piwheels.org/simple/tidalapi/tidalapi-0.6.10-py3-none-any.whl (12 kB)
Requirement already satisfied: Mopidy>=3.0 in /usr/lib/python3/dist-packages (from Mopidy-Tidal) (3.3.0)
Requirement already satisfied: Pykka>=1.1 in /usr/lib/python3/dist-packages (from Mopidy-Tidal) (2.0.3)
Installing collected packages: tidalapi, Mopidy-Tidal
Successfully installed Mopidy-Tidal-0.2.7 tidalapi-0.6.10
raspberrypi:/etc/mopidy $ sudo apt-get install gstreamer1.0-plugins-bad
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gstreamer1.0-plugins-bad is already the newest version (1.18.4-3).
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by tehkillerbee** [comment] 2022-09-13 07:28
@Wallmersbacher Usually, this is caused by the wrong python env. used when installing the plugin. Additionally, the pypi package has not been updated yet so you must install Mopidy-Tidal manually from the master branch. I will update the pypi package later this week.

```
pip3 install git+https://github.com/tehkillerbee/mopidy-tidal
```

**Comment by tehkillerbee** [comment] 2022-09-24 17:37
Closing this issue as no updates.

**Closed by tehkillerbee** 2022-09-24 17:37 UTC
