### ISSUE TITLE
Can't login to tidal

### ISSUE THREAD

**Issue by Glog78** [tehkillerbee/mopidy-tidal#43] opened 2022-01-18 18:04 UTC
tidalapi: Login failed: {"status":401,"error":"invalid_client","error_description":"Client with token *************** not found","sub_status":1005}
 401 Client Error: Unauthorized for url: https://auth.tidal.com/v1/oauth2/device_authorization

thats happening since today :(

**Comment by xmalbertox** [comment] 2022-01-18 18:42
Can confirm.
I believe to be an issue with the api tokens/keys used by [tamland/python-tidal](https://github.com/tamland/python-tidal)

The full error was:

```
ERROR    2022-01-18 15:30:22,789 [5825:TidalBackend-6 (_actor_loop)] tidalapi
  Login failed: {"status":401,"error":"invalid_client","sub_status":1005,"error_description":"Client with token **************** not found"}
ERROR    2022-01-18 15:30:22,790 [5825:TidalBackend-6 (_actor_loop)] pykka
  Unhandled exception in TidalBackend (urn:uuid:4c6797e0-963f-45b7-a0f6-a6f94755bfe6):
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pykka/_actor.py", line 179, in _actor_loop
    self.on_start()
  File "/usr/lib/python3.10/site-packages/mopidy_tidal/backend.py", line 68, in on_start
    self.oauth_login_new_session(oauth_file)
  File "/usr/lib/python3.10/site-packages/mopidy_tidal/backend.py", line 35, in oauth_login_new_session
    self._session.login_oauth_simple(function=logger.info)
  File "/usr/lib/python3.10/site-packages/tidalapi/__init__.py", line 210, in login_oauth_simple
    login, future = self.login_oauth()
  File "/usr/lib/python3.10/site-packages/tidalapi/__init__.py", line 223, in login_oauth
    login, future = self._login_with_link()
  File "/usr/lib/python3.10/site-packages/tidalapi/__init__.py", line 237, in _login_with_link
    request.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://auth.tidal.com/v1/oauth2/device_authorization
````

**Comment by Glog78** [comment] 2022-01-18 19:09
https://github.com/yaronzz/Tidal-Media-Downloader/issues/797#issuecomment-1015617361 , this helps if you change the tidal config api object acordingly ... but not sure for how long

**Comment by tehkillerbee** [comment] 2022-01-18 19:15
@Glog78 Thanks for letting me know about this. I have created an issue at python-tidal

**Comment by chicco64** [comment] 2022-01-19 09:46
i can confirm the same problem too, thanks

**Comment by tehkillerbee** [comment] 2022-01-19 14:38
It looks like python-tidal is not maintained any longer. At least, I have not seen much activity from the maintainer. Maybe it is time to switch to [pyopenTIDAL](https://github.com/Fokka-Engineering/pyopenTIDAL)?

**Comment by Glog78** [comment] 2022-01-19 14:45
if you want a small bugfix which makes it work again , i have one but i guess you don't want those keys in your codebase so maybe a switch would make sense.

**Comment by tehkillerbee** [comment] 2022-01-19 14:54
@Glog78 Exactly, I would like to avoid these keys in the codebase. A way forward could be to provide these keys in the mopidy config. 

You bring up a good point wrt. pyopenTIDAL. It would be nice to talk to the developer about packaging it/adding it to pypi.

**Comment by Glog78** [comment] 2022-01-19 14:58
For the moment  would not be a  bad idea to have 2 config lines more where people could add a client id and a client secret. 
If they are set you can load those from the config files else you can fall back to python-tidal (if the maintainer shows up again)
He not being active might be connected with 0.7 work (earlier) and maybe he has some health troubles currently.

**Comment by tehkillerbee** [comment] 2022-01-19 15:09
@Glog78 At the moment, python-tidal does not provide a way to set these variables externally. I am not aware of a way to override the client_id and client_secret class variables from outside python-tidal. 

Did you manage to find an easy way that does not require modifying python-tidal sources? In that case, feel free to share the PR (without the keys).

**Comment by Glog78** [comment] 2022-01-19 15:24
https://i.imgur.com/0tQTtk3.png << works like a charm ;)

**Comment by Glog78** [comment] 2022-01-19 16:15
https://termbin.com/szke << i hope this helps

**Comment by Glog78** [comment] 2022-01-19 16:33
pull request is up

**Comment by tehkillerbee** [comment] 2022-01-19 16:55
@Glog78 Woah, that was quick! I will take a look ASAP

**Comment by chicco64** [comment] 2022-01-19 17:44
Hi !
I just edited the following file by adding config.client_id //config.api_token//config.client_secret
# nano /usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py

Now mopidy tidal authenticates again, but I cannot play any audio files !

# journalctl -u mopidy | tail -5
-----------------------------------------------------------------------------------------------------------------
Jan 19 17:34:54 test-c mopidy[685]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 19 17:34:54 test-c mopidy[685]:   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
Jan 19 17:34:54 test-c mopidy[685]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Jan 19 17:34:54 test-c mopidy[685]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Jan 19 17:34:54 test-c mopidy[685]: WARNING  [Core-5] mopidy.core.tracklist Track is not playable: tidal:track:5575171:181327136:181327140
-----------------------------------------------------------------------------------------------------------------
Can you help me ?
many thanks !

**Comment by Glog78** [comment] 2022-01-19 17:47
@chicco64  wait a moment ... the pr is under review ;) once the pr is done you can update and just use
client_secret=somesecret
client_id=someid

in the config section of tidal in /etc/mopidy.conf or which other config file you use

**Comment by chicco64** [comment] 2022-01-19 17:49
I await the final instructions, thanks

**Comment by Glog78** [comment] 2022-01-19 18:05
@chicco64  also i advice you to read this https://github.com/yaronzz/Tidal-Media-Downloader/issues/797 carefully ... , also remember that your authorization is buffered and you might want to delete it first before you try a new client_secret / client_id.

If i am right and you did everything correctly the client_id / client_secret might not be the right one for your subscription.

**Comment by chicco64** [comment] 2022-01-19 18:15
I also tried to change the setting from quality = lossless to low but the player doesn't work
this is the error:

journalctl -u mopidy | tail -5
Jan 19 18:09:00 test-c mopidy[725]:     request.raise_for_status()
Jan 19 18:09:00 test-c  mopidy[725]:   File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
Jan 19 18:09:00 test-c  mopidy[725]:     raise HTTPError(http_error_msg, response=self)
Jan 19 18:09:00 test-c  mopidy[725]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/tracks/181327140/streamUrl?sessionId=089799b3-a7ea-482b-9e9b-9ea0012d9216&countryCode=ES&limit=999&soundQuality=LOW
Jan 19 18:09:00 test-c  mopidy[725]: WARNING  [Core-5] mopidy.core.tracklist Track is not playable: tidal:track:5575171:181327136:181327140

After inserting the new credentials as you indicated in the "gif photo" obviously I had to recreate the authorization json code.

my subscription is correct it always worked until yesterday

**Comment by Glog78** [comment] 2022-01-19 18:32
@chicco64  it's not your subscription ... but there are multiple client id / client secret combinations with different possibilities. The client id / client secret pair mentioned in the other project  seems to only work with people having a  master subscription.  My guess is your subscription is for looseless so you might need to use a different client id / client secret pair. I am not sure if it works but i would remove ~/.config/tidal-oauth.json and try out the id / secret pair very openly mention in this project -> https://github.com/Fokka-Engineering/libopenTIDAL :)

**Comment by tehkillerbee** [comment] 2022-01-19 19:19
@Glog78 @chicco64 This issue has also been fixed by the author of tidalapi. Make sure to update to the latest version. 

The PR works, but its challenging finding a client_id, client_secret combination that works correctly.

**Closed** 2022-01-19 20:09 UTC
